import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import { authRouter } from "./auth.js";
import { usersRouter } from "./users.js";
import { clientsRouter } from "./clients.js";
import { containersRouter } from "./containers.js";
import { approvalsRouter } from "./approvals.js";
import { myTasksRouter } from "./my-tasks.js";
import { analyticsRouter } from "./analytics.js";
import { reportsRouter } from "./reports.js";
import { timelineRouter } from "./timeline.js";
import { tasksRouter } from "./tasks.js";
import { documentsRouter } from "./documents.js";
import { intelligenceRouter } from "./intelligence.js";
import { sectionsRouter } from "./sections.js";
import { settingsRouter } from "./settings.js";
import { notificationsRouter } from "./notifications.js";
import { invoicesRouter } from "./invoices.js";
import { trackingRouter } from "./tracking.js";
import { searchRouter } from "./search.js";
import { dutyPaymentsRouter } from "./duty-payments.js";
import { banksRouter } from "./banks.js";
import { overheadExpensesRouter } from "./overhead-expenses.js";
import { containerExpensesRouter } from "./container-expenses.js";
import { branchesRouter } from "./branches.js";
import { paymentSchedulesRouter } from "./payment-schedules.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(clientsRouter);
router.use(containersRouter);
router.use(approvalsRouter);
router.use(myTasksRouter);
router.use(analyticsRouter);
router.use(reportsRouter);
router.use(timelineRouter);
router.use(tasksRouter);
router.use(documentsRouter);
router.use(intelligenceRouter);
router.use(sectionsRouter);
router.use(settingsRouter);
router.use(notificationsRouter);
router.use(invoicesRouter);
router.use(trackingRouter);
router.use(searchRouter);
router.use(dutyPaymentsRouter);
router.use(banksRouter);
router.use(overheadExpensesRouter);
router.use(containerExpensesRouter);
router.use(branchesRouter);
router.use(paymentSchedulesRouter);

export default router;
